# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LU信号处理.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction,QMainWindow,QFileDialog,QTextEdit,QMessageBox
from PyQt5.QtWidgets import QApplication

import pandas as pd
import numpy as np

import original_UI

class Ui_MainWindow(original_UI.Ui_MainWindow):

    def new_set_UI(self,mainWindow):
        self.setupUi(mainWindow)

        #菜单栏 File
        #open new file
        self.actionopen_new_file.triggered.connect(self.open_file)

        #按钮 导入数据
        self.column_number_value.setText('1')
        self.import_data_button.clicked.connect(self.import_data)

        #按钮 数据列数改变 ← →
        self.last_column_button.clicked.connect(self.column_number_minus)
        self.next_column_button.clicked.connect(self.column_number_plus)

    #函数 打开文件对话窗 将路径保存至文件路径栏
    def open_file(self):
        #注意，这里参数必须传入self.centralwidget，因为QFileDialog只接受widget参数
        file_name = QFileDialog.getOpenFileName(self.centralwidget,'选择文件','','Excel files(*.xlsx , *.xls)')
        self.file_path_value.setText(file_name[0])

    #函数 按文件路径栏已储存的路径将文件数据导入
    def import_data(self):
        try:
            self.file_data = pd.read_excel(self.file_path_value.text())
            self.file_data = np.array(self.file_data)
            QMessageBox.information(self.centralwidget, '提示', '数据导入成功')
        except:
            QMessageBox.information(self.centralwidget, '提示', '文件路径有误')

    #函数 数据列数减1
    def column_number_minus(self):
        num = int(self.column_number_value.text())
        if num > 1:
            num -= 1
        self.column_number_value.setText(str(num))

    #函数 数据列数加1
    def column_number_plus(self):
        num = int(self.column_number_value.text())
        num += 1
        self.column_number_value.setText(str(num))

